"""Generate the prom recording rule that materialises `clarion_entity_info`
from OTLP `target_info`.

This is mostly a static template — the only plan-specific bit is the rule
group name. The recording rule selects rows from `target_info` (which OTLP
emits automatically for each unique resource attribute set) and projects
them into the labelset that the model rules' `definedBy` queries expect.

If the entity emitter pushes `clarion_entity_info` directly as a gauge
(which it does — see `emitter.py`), this recording rule is technically
redundant but harmless: it produces the same series with the same labels.
We push it anyway so that *any* OTLP emitter wiring `clarion.*` resource
attributes (not just our own) will materialise entities. Reusable.
"""

from __future__ import annotations

from uuid import UUID

import yaml

from proj_clarion.schemas import DemoPlan


def build_prom_rules(plan: DemoPlan) -> str:
    """Return the prom-rules YAML body, ready for `gcx kg prom-rules create -f -`."""
    plan_id = str(plan.plan_id)
    # Note on uniqueness: Asserts dedups *recording-rule record names*
    # globally across all custom rule files in the tenant — not group names
    # or file names. Pushing a second plan's file while a previous plan's
    # is still installed therefore fails with HTTP 422 "duplicate of an
    # existing rule in custom rule file '<other-plan>.yaml'". Each plan's
    # file uses the plan_id prefix in its name (so files don't clobber),
    # and orphan-cleanup must remove old files before a new push. The
    # record name `clarion_entity_info` is intentionally stable so the
    # model rules' definedBy queries hit a single series.
    rule_group = {
        "name": "clarion.entity.presence",
        "interval": "1m",
        "rules": [
            {
                "record": "clarion_entity_info",
                "expr": (
                    "group by (\n"
                    "  clarion_store_id, clarion_region_id, clarion_channel_id,\n"
                    "  clarion_fulfillment_center_id, clarion_kube_cluster,\n"
                    "  clarion_service_id, service, namespace,\n"
                    "  asserts_env, asserts_site\n"
                    ") (\n"
                    "  label_replace(\n"
                    "    label_replace(\n"
                    "      target_info{asserts_env!=\"\"},\n"
                    '      "service",   "$1", "job", ".+/(.+)"\n'
                    "    ),\n"
                    '    "namespace", "$1", "job", "(.+)/.+"\n'
                    "  )\n"
                    ")"
                ),
            },
            # Pod variant
            {
                "record": "clarion_entity_info",
                "expr": (
                    "group by (\n"
                    "  clarion_pod_id, clarion_service_id, namespace,\n"
                    "  clarion_kube_cluster, asserts_env, asserts_site\n"
                    ") (\n"
                    "  target_info{clarion_pod_id!=\"\", asserts_env!=\"\"}\n"
                    ")"
                ),
            },
            # VM variant
            {
                "record": "clarion_entity_info",
                "expr": (
                    "group by (\n"
                    "  clarion_vm_id, clarion_kube_cluster, asserts_env, asserts_site\n"
                    ") (\n"
                    "  target_info{clarion_vm_id!=\"\", asserts_env!=\"\"}\n"
                    ")"
                ),
            },
        ],
    }

    doc = {
        "name": f"clarion-entity-recording-rules-{plan_id[:8]}",
        "groups": [rule_group],
    }
    header = (
        f"# gcx kg prom-rules create -f prom-rules.yaml\n"
        f"# Generated by Proj Clarion for plan_id={plan_id}\n"
        f"# Materialises clarion_entity_info from OTLP target_info for any emitter\n"
        f"# that sets clarion.* resource attributes. The entity emitter writes the\n"
        f"# gauge directly too — this recording rule is the safety net for other\n"
        f"# sources (Alloy, Otel collector pipelines).\n"
    )
    return header + yaml.dump(doc, sort_keys=False, default_flow_style=False, width=100)
