"""Atomic .env writer + in-process environment refresh.

Three jobs:
  - Resolve the path to the canonical `.env` (project root).
  - Write candidate values atomically: tmp file + rename, with a
    `.env.bak` snapshot of the previous file before overwriting.
  - After save, reload `os.environ` so the running API picks up the new
    values without a restart.
"""

from __future__ import annotations

import os
import shutil
from pathlib import Path
from typing import Iterable

from proj_clarion.api.setup.schema import REQUIRED_KEYS, SETUP_KEYS_BY_KEY


def _project_root() -> Path:
    """Resolve the project root by walking up from this file until we
    find the pyproject.toml. Falls back to CWD if not found (e.g. when
    the package is installed elsewhere)."""
    here = Path(__file__).resolve()
    for parent in (here, *here.parents):
        if (parent / "pyproject.toml").exists():
            return parent
    return Path.cwd()


def env_path() -> Path:
    """Where the canonical `.env` lives. Project root unless overridden
    by `CLARION_ENV_FILE` (used by tests + advanced users)."""
    override = os.environ.get("CLARION_ENV_FILE", "").strip()
    if override:
        return Path(override).expanduser().resolve()
    return _project_root() / ".env"


def is_setup_complete() -> bool:
    """True when every required env key has a non-empty value in the
    current process environment."""
    for key in REQUIRED_KEYS:
        if not (os.environ.get(key) or "").strip():
            return False
    return True


def _read_existing_env(path: Path) -> dict[str, str]:
    """Read existing `.env` into a map. We re-emit ANY key found here
    (even unknown ones) so users with custom keys don't lose them on
    save. Returns `{}` when the file doesn't exist.

    Handles multi-line quoted values — important because real-world .env
    files (especially long allow-lists like `RESEARCH_ALLOWED_HOSTS=...`)
    sometimes wrap a quoted value across many lines. The earlier reader
    only `splitlines()`'d and silently dropped continuation lines, which
    on save+rewrite truncated the value to whatever was on the first
    line. Now we accumulate until the matching closing quote.
    """
    if not path.exists():
        return {}
    out: dict[str, str] = {}
    raw_text = path.read_text(encoding="utf-8")
    i = 0
    lines = raw_text.splitlines(keepends=False)
    while i < len(lines):
        line = lines[i].strip()
        i += 1
        if not line or line.startswith("#") or "=" not in line:
            continue
        key, _, value = line.partition("=")
        key = key.strip().removeprefix("export ").strip()
        value = value.strip()
        # Multi-line value: opens with a quote and the closing quote
        # is on a LATER line. Keep consuming until we find it.
        if value and value[0] in ("'", '"'):
            quote = value[0]
            value = value[1:]
            # Already-closed on the same line: `KEY="x"` (or `KEY=""`).
            if value.endswith(quote) and not value.endswith("\\" + quote):
                value = value[:-1]
            else:
                # Accumulate continuation lines (with their original
                # newlines) until the closing quote.
                parts = [value]
                while i < len(lines):
                    cont = lines[i]
                    i += 1
                    if cont.rstrip().endswith(quote) and not cont.rstrip().endswith("\\" + quote):
                        parts.append(cont.rstrip()[:-1])
                        break
                    parts.append(cont)
                value = "\n".join(parts)
        elif value:
            value = value.strip("'\"")
        if key:
            out[key] = value
    return out


def _render_env_lines(values: dict[str, str]) -> str:
    """Format the values back into `.env` text, grouped by setup-schema
    section so the file stays readable. Unknown keys (i.e. ones not in
    SETUP_KEYS) get a trailing "Custom" section."""
    sections: dict[str, list[str]] = {}
    for setup_key in SETUP_KEYS_BY_KEY.values():
        if setup_key.key in values:
            sections.setdefault(setup_key.group, []).append(setup_key.key)

    custom_keys = sorted(set(values) - set(SETUP_KEYS_BY_KEY))

    GROUP_HEADERS = {
        "anthropic":     "# === Anthropic ===\n",
        "grafana_cloud": "# === Grafana Cloud ===\n",
        "sigil":         "# === Sigil (AI observability) — optional ===\n",
        "pdc":           "# === PDC (private datasource) — optional ===\n",
        "advanced":      "# === Advanced ===\n",
    }
    GROUP_ORDER = ("anthropic", "grafana_cloud", "sigil", "pdc", "advanced")

    lines: list[str] = [
        "# Generated by Clarion setup wizard. Edit manually if you know\n",
        "# what you're doing; otherwise use the /setup page in the UI.\n",
        "\n",
    ]
    for group in GROUP_ORDER:
        keys = sections.get(group, [])
        if not keys:
            continue
        lines.append(GROUP_HEADERS[group])
        for k in keys:
            lines.append(_render_kv(k, values[k]))
        lines.append("\n")
    if custom_keys:
        lines.append("# === Custom (not in setup schema) ===\n")
        for k in custom_keys:
            lines.append(_render_kv(k, values[k]))
    return "".join(lines)


def _render_kv(key: str, value: str) -> str:
    """Render one `KEY=VALUE` line. Quotes values containing spaces or
    shell metacharacters. Newlines are preserved AS-IS inside a quoted
    block (the OS shell's `source .env` won't grok it, but Python's
    `dotenv` parser does — and that's the only consumer the API uses).
    Always quoting when a newline is present is the critical bit: an
    unquoted multi-line value would be silently truncated next read.
    """
    needs_quote = any(c in value for c in ' "\'#$`\n')
    if not needs_quote:
        return f"{key}={value}\n"
    # Inside double-quotes, escape only the literal `"` and `\` —
    # everything else (including newlines and `$`) survives because
    # dotenv parses it as a single value bounded by the quotes.
    escaped = value.replace("\\", "\\\\").replace('"', '\\"')
    return f'{key}="{escaped}"\n'


def save_env(
    candidate: dict[str, str],
    *,
    merge: bool = True,
) -> tuple[Path, Path | None]:
    """Write `candidate` to `.env` atomically.

    Args:
      candidate: KEY→VALUE map. Empty-string values delete the key.
      merge:     when True (default), merge `candidate` onto the existing
                 `.env` so users adding one new field don't wipe the rest.
                 When False, the new file contains exactly `candidate`.

    Returns:
      (env_path, backup_path | None) — backup is None if no prior .env
      existed.
    """
    path = env_path()
    backup: Path | None = None
    existing = _read_existing_env(path) if merge else {}

    if path.exists():
        # Backup path. Earlier this used `path.with_suffix(".env.bak")`,
        # which because `.env` has no suffix per pathlib semantics PRODUCED
        # `.env.env.bak` (appending instead of replacing). The user
        # logically looked for `.env.bak`, didn't find it, and couldn't
        # restore from their backup. Use a literal sibling path instead.
        backup = path.parent / f"{path.name}.bak"
        # If a .env.bak already exists from a prior save, overwrite it —
        # we only keep ONE backup generation. Versioned backups are overkill
        # for a personal-config file and accumulate forever otherwise.
        shutil.copy2(path, backup)

    # Merge candidate over existing. Empty-string candidate values DELETE
    # the key (deliberate — the UI uses this to remove a misconfigured
    # token without prompting the user to "edit then blank").
    merged = dict(existing)
    for k, v in candidate.items():
        if v == "":
            merged.pop(k, None)
        else:
            merged[k] = v

    text = _render_env_lines(merged)

    # Atomic write: tmp file in the same dir, then rename. Rename is
    # atomic on POSIX, so concurrent readers either see the old file or
    # the new one, never a partial write.
    tmp = path.with_suffix(".env.tmp")
    tmp.write_text(text, encoding="utf-8")
    # Lock down perms so the file is owner-readable only.
    os.chmod(tmp, 0o600)
    os.replace(tmp, path)
    return path, backup


def refresh_environment() -> Iterable[str]:
    """Re-read the .env file into `os.environ` so the running API picks
    up the new values without a restart.

    Yields the names of keys that changed (added or value-updated). Used
    by the /api/setup/save route to log what shifted (without logging
    VALUES — those stay secret).
    """
    path = env_path()
    if not path.exists():
        return []
    new_values = _read_existing_env(path)
    changed: list[str] = []
    for k, v in new_values.items():
        if os.environ.get(k) != v:
            os.environ[k] = v
            changed.append(k)
    # Also unset any keys that were in env but no longer in file. Skip
    # variables we didn't put there (system PATH etc.) by only touching
    # keys we know about in our schema.
    from proj_clarion.api.setup.schema import SETUP_KEYS_BY_KEY
    for k in SETUP_KEYS_BY_KEY:
        if k not in new_values and os.environ.get(k):
            os.environ.pop(k, None)
            changed.append(k)
    return changed
